### PR TITLE
Job{,List}: Link to job archive directories

### PR DESCRIPTION
**Pull request by zmc**
This is more helpful than linking directly to teuthology.log, which may not even exist yet.

### CODE REVIEW

**Review by kamoltat — COMMENTED** [review]
@zmc 

NIT:
I think the text link is not so obvious since it is near the linked job name which is the same color. Maybe for aesthetic purposes we can have the archive link as an icon? or even different color? WDYT?

image

**Comment by VallariAg** [comment]
Maybe we can use an archive/folder icon which vertically aligns with the status icon above, like:
Screenshot 2023-08-16 at 9 20 47 AM

**Comment by zmc** [comment]
Thanks for the feedback @kamoltat and @VallariAg! Let me know what you think of the latest commit.

**Review by kamoltat — APPROVED** [review]
@zmc just need a rebase then it's good to go

**Review by VallariAg — APPROVED** [review]

**Pull request merged**
