### PR TITLE
RunList: use Custom filter

### PR DESCRIPTION
**Pull request by VallariAg**
- Use custom filter to show filter inputs outside the table
- Add a button to expand/hide filter options
- Display sort button only on hover over the column title
- Disable column action buttons (all of it's functions can be performed with sort, filter, and show/hide column buttons on corner-right)
   Column Action button options:
   image

Output:
image

### CODE REVIEW

**Comment by zmc** [comment]
Good start! I think this will end up being a better UI than the default. Some early feedback:
* the new toggle button jumps around when the filters are shown/hidden
* the _old_ toggle button (inside the table) is still present but nonfunctional
* the filter icon present in filtered columns is cut off; maybe it can be removed
* I think it would be good to group filters up logically, e.g.:
  * one group for "inputs" like branch, hash, suite - also scheduled date
  * a second group for "outputs" like status and ideally job counts (like runs with >N failed jobs)
  
What do you think?

**Comment by VallariAg** [comment]
Got it! All of these sound great, I'll start to work on these. 

> ideally job counts (like runs with >N failed jobs)

This would be harder to do right now because RunList has server side filtering. Even for "filter by username", I am working on adding username filter to paddles so we can support it in pulpito-ng. So I'll probably not include filter-by-job-counts in this PR but I can open a ticket for this because it sounds like a good idea. 
I see the idea behind this grouping and it makes sense! 

Another grouping that I was considering: 
1. Build info: hash, branch
2. Run info: suite, machine_type, schedule_date
3. Results: status, job_counts

**Comment by zmc** [comment]
I think these changes look good. I wonder if we might want the filter box to be just slightly more compact, and also if we should show a count of active filters on the button label so that it's apparent that there are filters active if you were to visit a URL with filters in the query parameters, e.g. https://pulpito-ng-pr-84.onrender.com/?machine_type=mira might use "Show filters (1)". What do you think?

Also - the machine type filter doesn't seem to work.

**Comment by VallariAg** [comment]
@zmc thank you for the review! I've fixed the things you mentioned and improved the filter menu UI. 
Render deployment here looks outdated, not sure why. Here's what it looks like: 

image

**Review by zmc — APPROVED** [review]
Looks great, thank you for making those changes!

**Pull request merged**
