### PR TITLE
public/favicon.ico: Update favicon to original pulpito icon

### PR DESCRIPTION
**Pull request by Devansh3712**
This PR is a fix for issue #8 where the favicon was the same as the Ceph icon but is now replaced with the original Pulpito site logo.

pulpito-white

### CODE REVIEW

**Review by zmc — APPROVED** [review]
Good work, thanks! :)

I filed an issue as a reminder that we should make an SVG version of the icon at some point.

**Review by zmc — CHANGES_REQUESTED** [review]
I just noticed the merge commit - could you drop that and rebase instead?

**Comment by kamoltat** [comment]
@Devansh3712 
One of your commits contain https://github.com/ceph/pulpito-ng/pull/15/commits/9b50cdbbf2ec1c4a27f2c7ce489800dd4ffff8ce
may I ask why?

**Review by kamoltat — CHANGES_REQUESTED** [review]
PR contains irrelevant commit

**Pull request closed without merging**
