### PR TITLE
JobList: Hover on status col shows failure reason

### PR DESCRIPTION
**Pull request by zmc**
This truncates the longer strings to 200 chars.

### CODE REVIEW

**Review by kamoltat — COMMENTED** [review]
@zmc 
One minor thing, when the failure description gets a bit long you often end up with the failure looking like this:

image

I think the purpose of hover show failure reason is to save the user the hassle of clicking into the actual job and look at the failure reason

**Comment by zmc** [comment]
@kamoltat I chose an arbitrary 200-char limit to display before chopping the string, in order to avoid the tooltip from getting unreasonably large. Sounds like a larger number would be good - what do you think?

**Comment by zmc** [comment]
@yuriw I would love your feedback on this as well

**Comment by zmc** [comment]
@kamoltat ping

**Comment by kamoltat** [comment]
@zmc The longest I've seen is 701 characters long. I think we can try 800? if it doesn't look to ugly

**Comment by kamoltat** [comment]
tested with 800 char

image

**Comment by zmc** [comment]
@kamoltat Thanks - re-pushed with the 800 char limit.

**Review by kamoltat — APPROVED** [review]
LGTM

**Pull request merged**
