### PR TITLE
Tooling updates

### PR DESCRIPTION
**Pull request by zmc**
Here we're upgrading:

* react from v17 to v18
* react-scripts to vite
* react-query from v3 to v4
* mui's styling library to what they now recommend
* some TS/linter packages

Builds should be faster and smaller; the dev server's reloads should be faster
Resolves: #1, resolves: #5, resolves: #12

### CODE REVIEW

**Comment by zmc** [comment]
I haven't found regressions using the PR server, so I'll un-draft this.

**Comment by zmc** [comment]
Ah, I just realized pagination in some of the tables is broken. I think that may have been broken before, but I know `DataGrid`'s behavior has changed so I'll fix it in this PR.

**Comment by zmc** [comment]
The commits I just pushed fix pagination, filtering, and deep-linking.

**Comment by kamoltat** [comment]
@zmc we have merge conflict in src/pages/Run/index.tsx

**Comment by kamoltat** [comment]
I was testing this and encountered a bug when you click on the queue page, it just becomes a white page for me

**Comment by zmc** [comment]
@kamoltat I fixed the queue page bug

**Comment by kamoltat** [comment]
@zmc 
Saw that, thank you!

**Comment by kamoltat** [comment]
@zmc one minor thing, I think the filter by date widget is still not aligned with the rest, I've noticed this before the PR change so it definitely is a known issue.
image

**Comment by zmc** [comment]
@kamoltat Good catch on both counts - I've pushed commits to fix them.

**Comment by Med16-11** [comment]
I have also raised the PR #30 for the datefilter box issue #10. This might create conflicts. Let me know if you want me to make any changes.

**Comment by kamoltat** [comment]
> I have also raised the PR #30 for the datefilter box issue #10. This might create conflicts. Let me know if you want me to make any changes.

@Med16-11 I think the conflict is pretty trivial to resolve.

**Comment by zmc** [comment]
@kamoltat I resolved the conflict

**Review by kamoltat — APPROVED** [review]
LGTM

**Pull request merged**
